### ISSUE TITLE
how to download it?

### ISSUE THREAD

**Issue by Krovohuii** [ArjuLaka/acode-plugin-renpy#1]
I downloaded all the files that are in the repository, moved them to the "plugins" folder, but Acode just stopped running.

**Comment by ArjuLaka** [comment]
Lol I have no idea how you found this, but this plugin has not been officially released yet. So this plugin is under development and still has a lot of bugs that I have no time to fix.

So if you want to download this plugin, you could try clone this repository, 
```
git clone https://github.com/ArjuLaka/acode-plugin-renpy
```
then run
```
npm i
```
Then build the plugin by running this command,
```
npm run build
```
After that, dist.zip file should have been appear. Then:
1. Open Acode Editor application
2. Then go to Settings > Plugin > add plugin > local
3. Then find the dist.zip file
4. Then click install
5. Restart the Acode Editor, and you should be good

Sorry for the confusion, I'm still learning how to develop a plugin. If you have a problem still, you can contact me via WhatsApp/Discord.

**Comment by Krovohuii** [comment]
Thx. and I found this plugin somehow by accident :)

**Comment by ArjuLaka** [comment]
No problem mate, glad to hear... :)
